### ISSUE TITLE
OSError when /tmp and actual destination are different devices

### ISSUE THREAD

**Issue by smetj** [peter-wangxu/persist-queue#46]
Hi,

If both `/tmp` and the directory holding the queue are located on separate devices you get following error:

```
Traceback (most recent call last):
  File "push.py", line 51, in <module>
    main()
  File "push.py", line 47, in main
    q.put(b'a')
  File "/home/smetj/data/python/virtualenv/default/lib/python3.6/site-packages/persistqueue/queue.py", line 107, in put
    self._put(item)
  File "/home/smetj/data/python/virtualenv/default/lib/python3.6/site-packages/persistqueue/queue.py", line 125, in _put
    self._saveinfo()
  File "/home/smetj/data/python/virtualenv/default/lib/python3.6/site-packages/persistqueue/queue.py", line 219, in _saveinfo
    os.rename(tmpfn, self._infopath())
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp9r_95kn4' -> 'blah/info'
```

**Comment by peter-wangxu** [comment]
Hi @smetj 

This can be resolved by adding the extra `tempdir` parameter when initializing the Queue:

```python
class Queue(object):
    def __init__(self, path, maxsize=0, chunksize=100, tempdir=None):
```

Let me know if this fulfill your requirement.

Thanks
Peter

**Comment by peter-wangxu** [comment]
Closing it now, reopen if the issue still occurs
