### ISSUE TITLE
Bug happens when storing queue in different file system

### ISSUE THREAD

**Issue by quangdatv** [peter-wangxu/persist-queue#59]
Hello, I got errors when storing queue data in different file system (`/tmp/` and my home folder are in different disks).

- Lib version persist-queue 0.4.0
- Code (filename `pq.py`):
```python
import persistqueue

if __name__ == "__main__":
    pq = persistqueue.Queue('somewhere')
    pq.put(444)
```

- Exception trace
```
Traceback (most recent call last):
  File "pq.py", line 5, in <module>
    pq.put(444)
  File "/home/dat/Workspace/ulti_monitor/venv/lib/python3.5/site-packages/persistqueue/queue.py", line 111, in put
    self._put(item)
  File "/home/dat/Workspace/ulti_monitor/venv/lib/python3.5/site-packages/persistqueue/queue.py", line 129, in _put
    self._saveinfo()
  File "/home/dat/Workspace/ulti_monitor/venv/lib/python3.5/site-packages/persistqueue/queue.py", line 223, in _saveinfo
    os.rename(tmpfn, self._infopath())
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpcq_fecb_' -> 'somewhere/info'
```

**Comment by aditya-novasignal** [comment]
I see that the issue is closed, I am getting the same error using version 0.5.1. How were you able to solve this?

**Comment by peter-wangxu** [comment]
This usually happens when in docker environment.
you can specify the (tmpdir='/abc') to solve it

**Comment by aditya-novasignal** [comment]
Thanks Peter! I ended up discovering the result shortly after at the below link, but I appreciate the response.

https://www.pythonanywhere.com/forums/topic/11248/
