### ISSUE TITLE
Failed to persist data when specifying a path on a different device

### ISSUE THREAD

**Issue by Murray-LIANG** [peter-wangxu/persist-queue#64]
We found some failure in OpenStack tests. In our environment, the Cinder service is running inside a docker container.
 
```bash
[root@samctl0 test]# tempest run --regex VolumesSnapshotTestJSON
......
{0} tearDownClass (tempest.api.volume.test_volumes_snapshots.VolumesSnapshotTestJSON) [0.000000s] ...
FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/tempest/test.py", line 224, in tearDownClass
        six.reraise(etype, value, trace)
      File "/usr/lib/python2.7/site-packages/tempest/test.py", line 196, in tearDownClass
        teardown()
      File "/usr/lib/python2.7/site-packages/tempest/test.py", line 562, in resource_cleanup
        raise testtools.MultipleExceptions(*cleanup_errors)
    testtools.runtest.MultipleExceptions: (<class 'tempest.lib.exceptions.DeleteErrorException'>, Resource 9ea09b32-6189-4701-823d-1dd392c10f87 failed to delete and is in ERROR status, <traceback object at 0x7f4c712114d0>)
```
Cinder logs showed : 
```bash
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/dell_emc/vnx/client.py", line 170, in delay_delete_lun
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server     self.queue.put(self.vnx.delete_lun, name=name)
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/storops/lib/tasks.py", line 47, in put
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server     self._q.put_nowait(item)
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/persistqueue/queue.py", line 124, in put_nowait
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server     return self.put(item, False)
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/persistqueue/queue.py", line 103, in put
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server     self._put(item)
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/persistqueue/queue.py", line 121, in _put
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server     self._saveinfo()
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/persistqueue/queue.py", line 216, in _saveinfo
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server     os.rename(tmpfn, self._infopath())
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server OSError: [Errno 18] Invalid cross-device link
2018-09-21 01:56:51.396 31 ERROR oslo_messaging.rpc.server 
```
From above log, `tmpfn` and `self._infopath()` passed to `os.rename` are two files on two devices.
In this case, `tmpfn` = `/tmp/xxxxx`, and `self._infopath()` = `/var/lib/cinder/xxxxx`

Inside docker, `/tmp` is an overlay filesystem, and `/var/lib/cinder` is on device `/dev/sda2`.

**Comment by Murray-LIANG** [comment]
Inside the container, 
```bash
()[root@samctl0 ~]# df -k /var/lib/cinder
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda2      291979244 15495944 276483300   6% /var/lib/cinder
()[root@samctl0 ~]# df -k /tmp
Filesystem     1K-blocks     Used Available Use% Mounted on
overlay        291979244 15495944 276483300   6% /
```

so, calling `rename` on `/tmp` and `/var/lib/cinder` failed. Actually we could recommend the user to pass in the path like #46. However, the user cannot guarantee that the path passed in is always on the same device as `/tmp` in any system.

For example, on system A, `/tmp` could be on device `/dev/sda1` and `/var/lib/cinder` could be on the same device `/dev/sda1`, then his/her program works fine. But on system B, `/tmp` could be on device `/dev/sda1`, while `/var/lib/cinder` could be on `/dev/sda2`, then his/her program doesn't work any more. 

Maybe we could use `shutil.move` here instead `rename`:
> shutil.move(src, dst)
Recursively move a file or directory (src) to another location (dst).

> If the destination is an existing directory, then src is moved inside that directory. If the destination already exists but is not a directory, it may be overwritten depending on os.rename() semantics.

> If the destination is on the current filesystem, then os.rename() is used. Otherwise, src is copied (using shutil.copy2()) to dst and then removed.

> New in version 2.3.

**Comment by peter-wangxu** [comment]
>If the destination is on the current filesystem, then os.rename() is used. Otherwise, src is copied (using shutil.copy2()) to dst and then removed.

Is the copy2 atomic? we need to keep Atomicity for the critical `info` file.

How about automatically changing the `tmp` dir to the same partition of the queue dir if they are not?


Thanks
Peter

**Comment by Murray-LIANG** [comment]
If the path is passed in like #46, can we dump the info to a temp file under that path, and then atomic rename to the actual info file?

Maybe we could pass in `tempdir` when initializing `Queue`.
```python
# The code in storops
self._q = persistqueue.Queue(self.path)

# We could use the below one
self._q = persistqueue.Queue(self.path, tempdir=self.path)
```

**Comment by peter-wangxu** [comment]
Git a try of above patch, it should solve the issue...:)

**Comment by peter-wangxu** [comment]
Closed by https://github.com/peter-wangxu/persist-queue/pull/69
